#!/usr/bin/env python
import sys

d = {}

for line in sys.stdin:
    line = line.rstrip().lstrip()
    if line in d:
        d[line] += 1
    else:
        d[line] = 1

for line in d.keys():
    print "%d %s" % (d[line], line)
