#!/usr/bin/env python
#
# Print all jira references in stdin
#

import os
import re
import sys

def main():
  while True:
    line = sys.stdin.readline()
    if not line:
      break

    m = re.match(r".*[\s]([A-Z]+)[- ](\d+)(.*)", line)
    if m:
      proj = m.group(1)
      num  = m.group(2)
      summary = m.group(3)
      print proj+"-"+num

  return 0


if __name__ == "__main__":
  sys.exit(main())
